require('babel-runtime/regenerator')
require('react-hot-loader/patch.js')
require('babel-register')
require('webpack-hot-middleware/client?reload=true')
require('./main.css')
require('./images/cat.jpg')
require('./index.html')
require('./app.js')
